"""Words many towns' own text and data share, translated once in the engine's string files
(site/strings/<language>.po) rather than in every town's [strings.<language>]: common boards,
officials' roles and seats, 311 categories, and the section summaries town configs copy.

A town's [strings.<language>] still wins (a town's "At-large" seats may be "Todo el municipio").
Numbered seats ("Ward 3", "Precinct 12", "District A") are translated by pattern: NUMBERED.
"""

import re

from pipeline.i18n import N_

TEXTS = frozenset((
    # Governing bodies and boards that many New England towns have.
    N_("City Council"),
    N_("Town Council"),
    N_("Board of Aldermen"),
    N_("Select Board"),
    N_("Board of Selectmen"),
    N_("School Committee"),
    N_("Board of Education"),
    N_("Planning Board"),
    N_("Planning Commission"),
    N_("Planning and Zoning Commission"),
    N_("Zoning Board of Appeals"),
    N_("Zoning Board of Adjustment"),
    N_("Board of Appeals"),
    N_("Conservation Commission"),
    N_("Inland Wetlands Commission"),
    N_("Board of Health"),
    N_("Historical Commission"),
    N_("Historic District Commission"),
    N_("Licensing Board"),
    N_("Board of Assessors"),
    N_("Board of Registrars"),
    N_("Retirement Board"),
    N_("Council on Aging"),
    N_("Committee on Aging"),
    N_("Community Preservation Committee"),
    N_("Finance Committee"),
    N_("Board of Finance"),
    N_("Board of Public Works"),
    N_("Traffic Commission"),
    N_("Housing Authority"),
    N_("Redevelopment Authority"),
    N_("Affordable Housing Trust"),
    N_("Commission on Disabilities"),
    N_("Disability Commission"),
    N_("Human Rights Commission"),
    N_("Cultural Council"),
    N_("Recreation Commission"),
    N_("Parks and Recreation Commission"),
    N_("Parks & Recreation Commission"),
    N_("Design Review Board"),
    N_("Open Space Committee"),
    N_("Economic Development Committee"),
    N_("Capital Improvement Committee"),
    N_("Cemetery Commission"),
    N_("Election Commission"),
    N_("Personnel Board"),
    N_("Library Board of Trustees"),
    N_("Board of Library Trustees"),
    N_("Airport Commission"),
    N_("Fair Rent Commission"),
    N_("City Council Committee of the Whole"),
    N_("City Council Economic Development Committee"),
    N_("City Council Public Safety Committee"),
    # Officials' roles and seats (role titles in the generic form: they label whoever holds them).
    N_("Mayor"),
    N_("Chair"),
    N_("Chairperson"),
    N_("Chairman"),
    N_("Vice Chair"),
    N_("Vice Chairperson"),
    N_("President"),
    N_("Vice President"),
    N_("Council President"),
    N_("Council Vice President"),
    N_("Secretary"),
    N_("Clerk"),
    N_("Treasurer"),
    N_("City Clerk"),
    N_("Town Clerk"),
    N_("Member"),
    N_("Citywide"),
    N_("At-large"),
    N_("Townwide"),
    N_("Appointed"),
    N_("Elected citywide for four years."),
    # 311 categories that many cities use.
    N_("Pothole"),
    N_("Graffiti"),
    N_("Other"),
    N_("Street Light"),
    N_("Streetlight Out"),
    # Section summaries and glossary definitions that town configs share.
    N_("Data sources, update schedule, metric definitions, and corrections."),
    N_("Where general fund money comes from and how it is spent, reserves, and the property tax limit."),
    N_("New homes permitted, home values and rents, affordable housing, and the housing stock."),
    N_("New homes permitted, home values and rents, and the housing stock."),
    N_("The mayor, City Council, and School Committee, by office and by ward, and how to reach them."),
    N_("Graduation, attendance, and MCAS results compared with the state."),
    N_("How fast the city responds to service requests, by category and ward."),
    N_("311 scorecard"),
    N_("city's Agenda Center"),
    N_("Meetings (Agenda Center)"),
    N_("A part of a public meeting closed to the public. State law allows it only for specific reasons, such as lawsuits, negotiations, or personnel matters."),
    N_("Massachusetts General Laws, the state's laws."),
    N_("The full City Council meeting as a committee, to discuss a matter before voting on it at a regular meeting."),
    N_("Americans with Disabilities Act, the federal law on access for people with disabilities."),
    N_("Community Preservation Act. A local property tax surcharge, with state matching money, that pays for open space, historic preservation, affordable housing, and recreation."),
))

# A seat or area with its number or letter: the English pattern, and its wording to translate.
NUMBERED = (
    (re.compile(r"Ward (\w{1,3})"), N_("Ward {n}")),
    (re.compile(r"Precinct (\w{1,3})"), N_("Precinct {n}")),
    (re.compile(r"District (\w{1,3})"), N_("District {n}")),
)
